# Generated by Django 5.0 on 2023-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID Аккаунта')),
                ('password', models.TextField(max_length=100, verbose_name='Пароль от аккаунта')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта от аккаунта')),
                ('proxy_address', models.TextField(max_length=32, verbose_name='Адрес proxy')),
                ('proxy_login', models.TextField(max_length=16, verbose_name='Логин proxy')),
            ],
            options={
                'verbose_name_plural': ('Аккаунты',),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('categories', models.TextField(max_length=32, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории парсинга',
            },
        ),
    ]
