# Generated by Django 5.0 on 2024-01-03 16:06

import Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_order', models.IntegerField(default=0, verbose_name='id заказа')),
                ('title', models.CharField(max_length=128, verbose_name='Название заказа')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('text', models.TextField(max_length=1024, verbose_name='Описание заказа')),
                ('files', models.FileField(upload_to=Orders.models.image_path, verbose_name='Файлы заказа')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('antiplug', models.TextField(max_length=32, verbose_name='Антиплагиат')),
                ('categories', models.TextField(max_length=64, verbose_name='Категория')),
                ('status', models.TextField(max_length=32, verbose_name='Статус заказа')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
