# Generated by Django 5.0 on 2024-01-03 16:20

import Orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_alter_orders_finish_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='finish_file',
            field=models.FileField(blank=True, default='', upload_to=Orders.models.finish_path, verbose_name='Законченные файлы'),
        ),
    ]
