# Generated by Django 5.0 on 2024-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_alter_orders_finish_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='message_from_customer',
            field=models.CharField(blank=True, default='', max_length=10000000000000, verbose_name='Сообщение от заказчика'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='antiplug',
            field=models.TextField(blank=True, max_length=32, verbose_name='Антиплагиат'),
        ),
    ]
