# Generated by Django 5.0 on 2023-12-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID Исполнителя')),
                ('tg_name', models.TextField(max_length=32, verbose_name='Телеграм аккаунт')),
                ('role', models.IntegerField(verbose_name='Роль')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('orders_finish', models.CharField(blank=True, max_length=1000000000000, verbose_name='Законченные заказы')),
                ('orders_in_progress', models.CharField(blank=True, max_length=1000000000000, verbose_name='Выполненные заказы')),
            ],
            options={
                'verbose_name_plural': 'Исполнители',
            },
        ),
    ]
