# Generated by Django 5.0 on 2023-12-24 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executor',
            options={'verbose_name': 'Исполнителя', 'verbose_name_plural': 'Исполнители'},
        ),
    ]
