# Generated by Django 5.0 on 2023-12-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0002_alter_executor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsTgBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_greetings', models.TextField(max_length=1024, verbose_name='Текст приветсвия')),
            ],
        ),
    ]
