# Generated by Django 5.0 on 2023-12-30 00:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0003_optionstgbot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionstgbot',
            options={'verbose_name': 'параметры', 'verbose_name_plural': 'Настройки TgBot'},
        ),
        migrations.RemoveField(
            model_name='optionstgbot',
            name='text_greetings',
        ),
        migrations.AddField(
            model_name='optionstgbot',
            name='options',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024, verbose_name='Параметр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionstgbot',
            name='values',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
