# Generated by Django 5.0 on 2023-12-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0004_alter_optionstgbot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='orders_in_progress',
            field=models.CharField(blank=True, max_length=1000000000000, verbose_name='Заказы в работе'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='role',
            field=models.CharField(choices=[('Админ', 'admin'), ('Исполнитель', 'executor')], max_length=11, verbose_name='Роль'),
        ),
    ]
