# Generated by Django 5.0 on 2023-12-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0006_alter_executor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Исполнитель', 'Исполнитель')], default='Исполнитель', max_length=13, verbose_name='Роль'),
        ),
    ]
