# Generated by Django 5.0 on 2024-01-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0007_alter_executor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='pay_history',
            field=models.CharField(blank=True, max_length=10000000000000000000000000, verbose_name='История платежей'),
        ),
    ]
