# Generated by Django 5.0 on 2024-01-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0008_executor_pay_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='orders_finish',
            field=models.CharField(blank=True, default=[], max_length=1000000000000, verbose_name='Законченные заказы'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='orders_in_progress',
            field=models.CharField(blank=True, default=[], max_length=1000000000000, verbose_name='Заказы в работе'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='pay_history',
            field=models.CharField(blank=True, default=[], max_length=10000000000000000000000000, verbose_name='История платежей'),
        ),
    ]
