# Generated by Django 5.0 on 2024-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0009_alter_executor_balance_alter_executor_orders_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='orders_in_progress',
            field=models.CharField(blank=True, default='', max_length=1000000000000, verbose_name='Заказы в работе'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='pay_history',
            field=models.CharField(blank=True, default='', max_length=10000000000000000000000000, verbose_name='История платежей'),
        ),
    ]
