# Generated by Django 5.0 on 2024-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0010_alter_executor_orders_in_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executor',
            name='orders_finish',
            field=models.CharField(blank=True, default='', max_length=1000000000000, verbose_name='Законченные заказы'),
        ),
    ]
