# Generated by Django 5.0 on 2024-01-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TgBot', '0013_alter_executor_orders_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='orders_pending',
            field=models.CharField(blank=True, default='', max_length=10000000000000000000000000, verbose_name='Заказы ожидающие подтверждения'),
        ),
    ]
